# Generated by Django 5.1.3 on 2026-04-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_fp',
        ),
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_org', to='orgs.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='orgs.county'),
        ),
    ]
