# Generated by Django 5.1.3 on 2026-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_location',
            name='loc_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
