# Generated by Django 5.2.8 on 2025-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_city_orglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
