# Generated by Django 5.1.3 on 2026-04-14 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 14)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 14)),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 14)),
        ),
    ]
