# Generated by Django 5.1.3 on 2026-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_pending_location_loc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawloaddata',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
