# Generated by Django 5.2.8 on 2025-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglocation',
            name='location_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orglocation',
            name='org_loc_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
