# Generated by Django 5.1.3 on 2026-04-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_activity_time_description_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField()),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 16)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 16)),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 16)),
        ),
    ]
