# Generated by Django 5.2.8 on 2025-12-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_orglocation_location_about_orglocation_org_loc_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('online', models.BooleanField(default=False)),
                ('loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventlocs', to='orgs.orglocation')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventorgs', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event_length', models.CharField(choices=[('H1', 'One Hour'), ('H2', '2-3 Hours'), ('H4', 'Half Day'), ('D1', 'Full Day'), ('D2', 'Multiple Days')], max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventsched', to='orgs.events')),
            ],
        ),
    ]
