# Generated by Django 5.1.3 on 2026-04-09 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_rawloaddata_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 9)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 9)),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 9)),
        ),
    ]
