# Generated by Django 5.1.3 on 2026-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_session_time_description_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_session',
            name='time_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='time_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
