# Generated by Django 5.2.8 on 2025-12-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_events_eventschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
