# Generated by Django 5.1.3 on 2026-04-18 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_feedback_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='ongoing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='session_format',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='state',
            field=models.CharField(blank=True, default='WI', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='time_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='validation_errors',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='validation_warnings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 18)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 18)),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='activity_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='date_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='no_cost',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
