# Generated by Django 5.2.8 on 2025-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglocation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
