# Generated by Django 5.1.3 on 2026-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_pending_session_time_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='state',
            field=models.CharField(blank=True, default='WI', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
