# Generated by Django 5.1.3 on 2026-04-19 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_rawloaddata_end_date_rawloaddata_ongoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 19)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(help_text="Your location can be used system-wide. You may want to include your organization name to help make it unique e.g., 'MyOrg Main Location'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 19)),
        ),
    ]
