# Generated by Django 5.1.3 on 2026-04-21 15:08

import datetime
import orgs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_activity_expire_date_alter_location_loc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=orgs.models.default_expire_date),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 21)),
        ),
    ]
