# Generated by Django 5.2.8 on 2025-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_orglocation_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('St', 'Statewide')], max_length=100),
        ),
    ]
