# Generated by Django 5.1.3 on 2026-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_rawloaddata_state_rawloaddata_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawloaddata',
            name='activity_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
