# Generated by Django 5.1.3 on 2026-04-24 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='no_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 24)),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_format',
            field=models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('b', 'Hybrid'), ('s', 'Self Selected Locations')], max_length=1),
        ),
    ]
