# Generated by Django 5.2.8 on 2025-12-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_region_name_alter_city_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglocation',
            name='physical_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('NE', 'Northeast'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('EC', 'East Central'), ('C', 'Central'), ('St', 'Statewide'), ('SW', 'Southwest')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('NE', 'Northeast'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('EC', 'East Central'), ('C', 'Central'), ('St', 'Statewide'), ('SW', 'Southwest')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='city',
            field=models.ForeignKey(default='Statewide', on_delete=django.db.models.deletion.CASCADE, to='orgs.city'),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='state',
            field=models.CharField(blank=True, default='WI', max_length=100),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
