# Generated by Django 5.1.3 on 2026-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_alter_rawloaddata_activity_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawloaddata',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
