# Generated by Django 5.1.3 on 2026-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_alter_rawloaddata_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
