# Generated by Django 5.1.3 on 2026-04-28 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_alter_activity_no_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawloaddata',
            old_name='no_cost',
            new_name='has_cost',
        ),
        migrations.RenameField(
            model_name='rawloaddata',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 28)),
        ),
    ]
