# Generated by Django 5.2.8 on 2025-12-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_orglocation_physical_location_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('C', 'Central'), ('SE', 'Southeast'), ('St', 'Statewide'), ('EC', 'East Central'), ('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('SW', 'Southwest')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('SE', 'Southeast'), ('St', 'Statewide'), ('EC', 'East Central'), ('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('SW', 'Southwest')], default='', max_length=100),
        ),
    ]
