# Generated by Django 5.1.3 on 2026-04-10 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_rawloaddata_ongoing_rawloaddata_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='validation_errors',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='validation_warnings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 10)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 10)),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='date_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='no_cost',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='ongoing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='online',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
