# Generated by Django 5.2.8 on 2025-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('EC', 'East Central'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('C', 'Central'), ('St', 'Statewide'), ('SC', 'South Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('EC', 'East Central'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('C', 'Central'), ('St', 'Statewide'), ('SC', 'South Central')], default='', max_length=100),
        ),
    ]
