# Generated by Django 5.2.8 on 2025-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('C', 'Central'), ('EC', 'East Central'), ('SC', 'South Central'), ('SW', 'Southwest'), ('St', 'Statewide'), ('NE', 'Northeast'), ('SE', 'Southeast'), ('NW', 'Northwest')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('SC', 'South Central'), ('SW', 'Southwest'), ('St', 'Statewide'), ('NE', 'Northeast'), ('SE', 'Southeast'), ('NW', 'Northwest')], default='', max_length=100),
        ),
    ]
