# Generated by Django 5.2.8 on 2025-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('SC', 'South Central'), ('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('St', 'Statewide')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('SC', 'South Central'), ('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
    ]
