# Generated by Django 5.1.3 on 2026-05-17 13:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_alter_pending_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 5, 17)),
        ),
        migrations.CreateModel(
            name='OrgInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor')], default='owner', max_length=20)),
                ('code', models.CharField(blank=True, max_length=80, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='orgs.organization')),
            ],
        ),
    ]
