# Generated by Django 5.2.8 on 2025-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('St', 'Statewide'), ('C', 'Central'), ('SW', 'Southwest'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('EC', 'East Central'), ('SE', 'Southeast'), ('SC', 'South Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('St', 'Statewide'), ('C', 'Central'), ('SW', 'Southwest'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('EC', 'East Central'), ('SE', 'Southeast'), ('SC', 'South Central')], default='', max_length=100),
        ),
    ]
