# Generated by Django 5.1.3 on 2026-05-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_activity_has_cost_alter_pending_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending_activity',
            old_name='no_cost',
            new_name='has_cost',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='no_cost',
        ),
    ]
