# Generated by Django 5.2.8 on 2025-12-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='org',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='event_length',
        ),
        migrations.AddField(
            model_name='event',
            name='instructors',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='addl_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventlocs', to='orgs.orglocation'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('St', 'Statewide'), ('SC', 'South Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('C', 'Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('NW', 'Northwest')], max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training'), ('m', 'Master Naturalist')], max_length=1),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('St', 'Statewide'), ('SC', 'South Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('C', 'Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('NW', 'Northwest')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='EventHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='orgs.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='orgs.organization')),
            ],
        ),
    ]
