# Generated by Django 5.1.3 on 2026-05-18 15:21

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_rename_no_cost_pending_activity_has_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginvite',
            name='code',
        ),
        migrations.RemoveField(
            model_name='orginvite',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='orginvite',
            name='used_at',
        ),
        migrations.AddField(
            model_name='orginvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationenrollmentrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 5, 18)),
        ),
    ]
