# Generated by Django 5.1.3 on 2026-05-19 13:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_remove_orginvite_code_remove_orginvite_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 5, 19)),
        ),
    ]
