# Generated by Django 5.2.8 on 2025-12-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_remove_event_loc_remove_event_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('C', 'Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide'), ('SC', 'South Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('EC', 'East Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide'), ('SC', 'South Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('EC', 'East Central')], default='', max_length=100),
        ),
    ]
