# Generated by Django 5.1.3 on 2026-05-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_alter_orginvite_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 5, 20)),
        ),
    ]
