# Generated by Django 5.2.8 on 2025-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_event_org_alter_city_region_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='training_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='volunteer_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(choices=[('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast  '), ('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('St', 'Statewide')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast  '), ('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('St', 'Statewide')], default='', max_length=100),
        ),
    ]
