# Generated by Django 5.2.8 on 2026-01-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_organization_training_url_organization_volunteer_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, choices=[('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast  '), ('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('St', 'Statewide')], default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='orgs.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='orgs.profile')),
            ],
        ),
    ]
