# Generated by Django 5.1.3 on 2026-05-22 13:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_activity_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_activity',
            name='time_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_session',
            name='source_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 5, 22)),
        ),
    ]
