# Generated by Django 5.1.3 on 2026-05-22 13:57

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0018_pending_activity_time_description_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE orgs_pending_location
                DROP CONSTRAINT IF EXISTS orgs_pending_location_loc_name_key;
            """,
            reverse_sql="""
                ALTER TABLE orgs_pending_location
                ADD CONSTRAINT orgs_pending_location_loc_name_key UNIQUE (loc_name);
            """,
        ),
    ]