# Generated by Django 5.1.3 on 2026-06-02 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_drop_pending_location_loc_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 6, 2)),
        ),
    ]
