# Generated by Django 5.2.8 on 2026-01-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_organization_owner_profile_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='starttime',
        ),
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='no_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='time_commitment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='EventHosts',
        ),
    ]
