# Generated by Django 5.1.3 on 2026-06-02 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_alter_pending_activity_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('visit', 'Page visit'), ('org_view', 'Organization viewed'), ('favorite_add', 'Favorite added'), ('favorite_remove', 'Favorite removed'), ('login_attempt', 'Login attempt'), ('signup_attempt', 'Signup attempt')], max_length=50)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action'], name='orgs_activi_action_be0b39_idx'), models.Index(fields=['created_at'], name='orgs_activi_created_f2b0e5_idx'), models.Index(fields=['org'], name='orgs_activi_org_id_6d7bec_idx')],
            },
        ),
    ]
