# Generated by Django 5.2.8 on 2026-01-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_remove_eventschedule_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglocation',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.city'),
        ),
    ]
