# Generated by Django 5.2.8 on 2026-02-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_alter_orglocation_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(blank=True, choices=[('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast  '), ('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('St', 'Statewide')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orglocation',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.county'),
        ),
    ]
