# Generated by Django 5.1.3 on 2026-06-03 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('visit', 'Page visit'), ('org_enroll', 'Organization enrollment'), ('favorite_add', 'Favorite added'), ('favorite_remove', 'Favorite removed'), ('login_attempt', 'Login attempt'), ('signup_attempt', 'Signup attempt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='activity_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 6, 3)),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='session_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
