# Generated by Django 5.1.3 on 2026-06-05 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 6, 5)),
        ),
    ]
