# Generated by Django 5.2.8 on 2026-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_county_orglocation_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orglocation',
            name='county',
        ),
        migrations.AddField(
            model_name='orglocation',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orglocation',
            name='county_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orglocation',
            name='region_name',
            field=models.CharField(blank=True, choices=[('SC', 'South Central'), ('NW', 'Northwest'), ('NE', 'Northeast  '), ('C', 'Central'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('EC', 'East Central'), ('SC', 'South Central'), ('St', 'Statewide')], max_length=100, null=True),
        ),
    ]
