# Generated by Django 5.1.3 on 2026-06-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_alter_activity_activity_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_uploads', to='orgs.profile'),
        ),
    ]
