# Generated by Django 5.2.8 on 2026-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_remove_orglocation_county_orglocation_city_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orglocation',
            name='city',
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='location_about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
