# Generated by Django 5.1.3 on 2026-06-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_activityupload_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.activityupload'),
        ),
        migrations.AddField(
            model_name='location',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.activityupload'),
        ),
        migrations.AddField(
            model_name='session',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.activityupload'),
        ),
    ]
