# Generated by Django 5.2.8 on 2026-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_commitment_event_date_event_orgloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inperson',
            field=models.BooleanField(default=True),
        ),
    ]
