# Generated by Django 5.1.3 on 2026-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_activity_source_upload_location_source_upload_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pending_location',
            name='unique_pending_location_fp',
        ),
        migrations.AlterField(
            model_name='pending_location',
            name='fingerprint',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='pending_location',
            constraint=models.UniqueConstraint(fields=('source_upload', 'fingerprint'), name='unique_pending_location_per_upload_fingerprint'),
        ),
    ]
