# Generated by Django 5.2.8 on 2026-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_event_date_description_event_inperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='WI_County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=2)),
            ],
        ),
    ]
