# Generated by Django 5.1.3 on 2026-06-06 18:17

import orgs.services.helper_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_remove_pending_location_unique_pending_location_fp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='activities_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='actvities_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='locations_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='locations_matched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='locations_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='sessions_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending_activity',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawloaddata',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=orgs.services.helper_function.default_expire_date),
        ),
    ]
