# Generated by Django 5.1.3 on 2026-06-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_activityupload_activities_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityupload',
            name='status',
            field=models.CharField(default='csv_load', max_length=20),
        ),
    ]
