# Generated by Django 5.2.8 on 2026-02-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_wi_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglocation',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.wi_county'),
        ),
    ]
