# Generated by Django 5.2.8 on 2026-02-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0028_orglocation_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orglocation',
            name='county',
        ),
        migrations.AddField(
            model_name='orglocation',
            name='county_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.county'),
        ),
        migrations.DeleteModel(
            name='WI_County',
        ),
    ]
