# Generated by Django 5.1.3 on 2026-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0028_alter_activityupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='database_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='load_errors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
