# Generated by Django 5.2.8 on 2026-02-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_remove_orglocation_county_orglocation_county_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orglocation',
            name='county_name',
        ),
    ]
