# Generated by Django 5.1.3 on 2026-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_activityupload_database_error_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
