# Generated by Django 5.2.8 on 2026-02-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_remove_orglocation_county_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglocation',
            name='county_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county', to='orgs.county'),
        ),
    ]
