# Generated by Django 5.1.3 on 2026-06-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='orgs.activityupload')),
            ],
        ),
    ]
