# Generated by Django 5.1.3 on 2026-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0031_uploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='step',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
