# Generated by Django 5.2.8 on 2026-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0031_alter_orglocation_county_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='orgs.eventcategory'),
        ),
    ]
