# Generated by Django 5.1.3 on 2026-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0032_uploadlog_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadlog',
            old_name='success_count',
            new_name='created_count',
        ),
        migrations.RenameField(
            model_name='uploadlog',
            old_name='total_rows',
            new_name='source_count',
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='matched_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='merged_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
