# Generated by Django 5.1.3 on 2026-06-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0033_rename_success_count_uploadlog_created_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='locations_merged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityupload',
            name='session_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
