# Generated by Django 5.2.8 on 2026-02-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0033_event_deleted_organization_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['county_name']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['org_name']},
        ),
        migrations.AlterModelOptions(
            name='orglocation',
            options={'ordering': ['loc_name']},
        ),
        migrations.AlterField(
            model_name='county',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
    ]
