# Generated by Django 5.1.3 on 2026-06-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0034_activityupload_locations_merged_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityupload',
            old_name='actvities_skipped',
            new_name='activities_skipped',
        ),
        migrations.RenameField(
            model_name='activityupload',
            old_name='session_skipped',
            new_name='sessions_skipped',
        ),
    ]
