# Generated by Django 6.0.2 on 2026-02-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0035_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='region_name',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='roles', to='orgs.eventcategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='orgs.organization')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
