# Generated by Django 5.1.3 on 2026-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0035_rename_actvities_skipped_activityupload_activities_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='load_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
