# Generated by Django 6.0.2 on 2026-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_alter_county_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrole',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_roles', to='orgs.eventcategory'),
        ),
    ]
