# Generated by Django 5.1.3 on 2026-06-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_activityupload_load_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_location',
            name='match_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pending_location',
            name='match_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='activityupload',
            name='status',
            field=models.CharField(choices=[('csv_load', 'CSV load'), ('csv_mapped', 'Mapped columns'), ('staged', 'Raw data staged'), ('raw_review', 'Raw data has been reviewed'), ('build_pending', 'Pending records built'), ('review_locations', 'Reviewing Pending locations'), ('review_activities', 'Reviewing Pending activities'), ('published', 'Published'), ('rollback', 'Published records rolled back'), ('error', 'Error'), ('canceled', 'Canceled before publish')], default='csv_load', max_length=30),
        ),
        migrations.AlterField(
            model_name='activityupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pending_location',
            name='processing_status',
            field=models.CharField(choices=[('confirmed', 'Matched existing location'), ('create', 'Create new location'), ('merge', 'Merge with selected location'), ('skip', 'Skip')], default='create', max_length=20),
        ),
    ]
