# Generated by Django 6.0.2 on 2026-02-27 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_alter_volunteerrole_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='orgloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolelocations', to='orgs.orglocation'),
        ),
    ]
