# Generated by Django 5.1.3 on 2026-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_pending_location_match_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('map_filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pending_location',
            name='processing_status',
            field=models.CharField(choices=[('match', 'Matched existing location'), ('create', 'Create new location'), ('merge', 'Merge with selected location'), ('skip', 'Skip')], default='create', max_length=20),
        ),
    ]
