# Generated by Django 6.0.2 on 2026-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_volunteerrole_orgloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='include_neighboring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='include_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='myregion',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], default='', max_length=100),
        ),
    ]
