# Generated by Django 5.1.3 on 2026-06-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_region_alter_pending_location_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='orgs.region'),
        ),
    ]
