# Generated by Django 6.0.2 on 2026-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_profile_include_neighboring_profile_include_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='include_neighboring',
        ),
    ]
