# Generated by Django 5.1.3 on 2026-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_county_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationenrollmentrequest',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
