# Generated by Django 5.1.3 on 2026-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0040_organizationenrollmentrequest_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityupload',
            name='activities_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityupload',
            name='locations_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityupload',
            name='sessions_created',
            field=models.IntegerField(default=0),
        ),
    ]
