# Generated by Django 6.0.2 on 2026-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0040_remove_profile_include_neighboring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='preferred_region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myregion',
        ),
    ]
