# Generated by Django 5.1.3 on 2026-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0041_alter_activityupload_activities_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='cat_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
