# Generated by Django 6.0.2 on 2026-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0041_rename_location_profile_preferred_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
