# Generated by Django 6.0.2 on 2026-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0042_volunteerrole_expire_date_volunteerrole_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
