# Generated by Django 5.1.3 on 2026-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0042_eventcategory_cat_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='categories',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_pending_activities', to='orgs.eventcategory'),
        ),
    ]
