# Generated by Django 5.1.3 on 2026-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0043_rawloaddata_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_activity',
            name='raw_category_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
