# Generated by Django 6.0.2 on 2026-03-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0043_alter_event_participant_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_url',
            new_name='url',
        ),
    ]
