# Generated by Django 6.0.2 on 2026-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0044_rename_event_description_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='date_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
