# Generated by Django 5.1.3 on 2026-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0044_pending_activity_raw_category_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawloaddata',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='time_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
