# Generated by Django 6.0.2 on 2026-03-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0045_volunteerrole_date_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('date_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='category_activities', to='orgs.eventcategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orgs.organization')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('session_format', models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('b', 'Hybrid')], max_length=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='orgs.activity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.orglocation')),
            ],
        ),
    ]
