# Generated by Django 6.0.2 on 2026-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0046_activity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='migrated_from_event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
