# Generated by Django 5.1.3 on 2026-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0046_alter_rawloaddata_date_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_loc_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='activity_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='date_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='raw_category_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='time_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pending_location',
            name='org_loc_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pending_location',
            name='processing_status',
            field=models.CharField(choices=[('match', 'Matched existing location'), ('create', 'Create new location'), ('merge', 'Merge with selected location'), ('skip', 'Skip')], default='create', max_length=50),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='session_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='activity_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
