# Generated by Django 5.1.3 on 2026-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0047_alter_activity_activity_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_commitment_txt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
