# Generated by Django 6.0.2 on 2026-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0047_volunteerrole_migrated_from_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='no_cost',
            field=models.BooleanField(default=False),
        ),
    ]
