# Generated by Django 5.1.3 on 2026-06-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_activity_time_commitment_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.region'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.region'),
        ),
    ]
