# Generated by Django 6.0.2 on 2026-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_activity_activity_url_activity_no_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='migrated_from_event',
        ),
        migrations.AddField(
            model_name='activity',
            name='migrated_from_event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
