# Generated by Django 6.0.2 on 2026-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0049_remove_volunteerrole_migrated_from_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateField(),
        ),
    ]
