# Generated by Django 5.1.3 on 2026-06-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0049_location_region_organization_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationenrollmentrequest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_master_naturalist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counties', to='orgs.region'),
        ),
    ]
