# Generated by Django 6.0.2 on 2026-03-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0050_alter_session_end_alter_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
