# Generated by Django 5.1.3 on 2026-06-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0050_organizationenrollmentrequest_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_region',
        ),
    ]
