# Generated by Django 6.0.2 on 2026-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0051_session_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
