# Generated by Django 5.1.3 on 2026-06-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0051_remove_profile_preferred_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff',
        ),
    ]
