# Generated by Django 6.0.2 on 2026-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0052_alter_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
