# Generated by Django 6.0.2 on 2026-03-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0053_session_ongoing'),
    ]

    operations = [
       migrations.RenameModel(
        old_name='OrgLocation',
        new_name='Location',
    )
    ]
