# Generated by Django 5.1.3 on 2026-06-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0053_alter_region_options_pending_location_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='organizationenrollmentrequest',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='pending_location',
            name='region_name',
        ),
    ]
