# Generated by Django 5.1.3 on 2026-07-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0054_remove_county_region_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
