# Generated by Django 6.0.2 on 2026-03-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0054_remove_orglocation_county_id_remove_orglocation_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='volunteerrole',
            name='org',
        ),
        migrations.RemoveField(
            model_name='volunteerrole',
            name='orgloc',
        ),
        migrations.RemoveField(
            model_name='volunteerrole',
            name='time_commitment',
        ),
        migrations.AlterField(
            model_name='location',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='orgs.organization'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='VolunteerRole',
        ),
    ]
