# Generated by Django 5.1.3 on 2026-07-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0055_activity_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='online',
        ),
    ]
