# Generated by Django 6.0.2 on 2026-03-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0055_remove_volunteerrole_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='physical_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='orgs.location'),
        ),
    ]
