# Generated by Django 5.1.3 on 2026-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0056_remove_activity_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawloaddata',
            name='session_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('v', 'Volunteer'), ('t', 'Learn')], max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_format',
            field=models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('s', 'Self Selected Locations')], max_length=1),
        ),
    ]
