# Generated by Django 6.0.2 on 2026-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0056_alter_location_org_alter_location_physical_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
