# Generated by Django 5.1.3 on 2026-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0057_rawloaddata_session_url_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawloaddata',
            name='session_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
