# Generated by Django 5.1.3 on 2026-07-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0058_alter_rawloaddata_session_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_format',
            field=models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('b', 'Hybrid'), ('s', 'Self Selected Locations')], max_length=1),
        ),
    ]
