# Generated by Django 6.0.2 on 2026-03-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0058_activity_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_acts', to='orgs.profile'),
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_locs', to='orgs.profile'),
        ),
    ]
