# Generated by Django 5.1.3 on 2026-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0059_alter_session_session_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
