# Generated by Django 5.1.3 on 2026-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0060_session_session_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='news_source',
            field=models.CharField(choices=[('rss', 'RSS'), ('newspage', 'News Page'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='news_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organizationenrollmentrequest',
            name='news_source',
            field=models.CharField(choices=[('rss', 'RSS'), ('newspage', 'News Page'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationenrollmentrequest',
            name='news_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
