# Generated by Django 6.0.2 on 2026-03-26 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0060_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='category_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 3, 26)),
        ),
    ]
