# Generated by Django 5.1.3 on 2026-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0061_organization_news_source_organization_news_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='news_source',
            field=models.CharField(choices=[('none', 'None'), ('rss', 'RSS Feed'), ('newspage', 'News Page'), ('email_newsletter', 'Email Newsletter')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationenrollmentrequest',
            name='news_source',
            field=models.CharField(choices=[('none', 'None'), ('rss', 'RSS Feed'), ('newspage', 'News Page'), ('email_newsletter', 'Email Newsletter')], default='none', max_length=20),
        ),
    ]
