# Generated by Django 6.0.2 on 2026-03-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0061_eventcategory_category_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor')], max_length=10)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed', to='orgs.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='orgs.profile')),
            ],
            options={
                'unique_together': {('profile', 'org')},
            },
        ),
    ]
