# Generated by Django 5.1.3 on 2026-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0062_emaillog_alter_organization_news_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('BLOCKED_HOURLY', 'Blocked Hourly'), ('BLOCKED_MONTHLY', 'Blocked Monthly'), ('DISABLED', 'Email Disabled'), ('FAILED', 'Send Failed')], default='SENT', max_length=30),
        ),
    ]
