# Generated by Django 6.0.2 on 2026-03-27 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0062_orgmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 3, 27)),
        ),
        migrations.AlterField(
            model_name='orgmanager',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor')], default='editor', max_length=10),
        ),
    ]
