# Generated by Django 5.1.3 on 2026-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0063_emaillog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
