# Generated by Django 6.0.2 on 2026-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0063_alter_activity_expire_date_alter_orgmanager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
