# Generated by Django 6.0.2 on 2026-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0064_alter_location_loc_name_alter_organization_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=255),
        ),
    ]
