# Generated by Django 5.1.3 on 2026-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0064_feedback_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='example_org',
            field=models.BooleanField(default=False),
        ),
    ]
