# Generated by Django 6.0.2 on 2026-03-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0065_alter_location_loc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
