# Generated by Django 5.1.3 on 2026-08-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0066_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
