# Generated by Django 5.1.3 on 2026-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0067_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audience',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
