# Generated by Django 6.0.2 on 2026-03-29 16:51

import django.db.models.deletion
from django.db import migrations, models
from django.db import migrations
from datetime import datetime

from orgs import apps

def backfill_fields(apps, schema_editor):
    Location = apps.get_model('orgs', 'Location')
    default_date = datetime(2026, 3, 1)

    for loc in Location.objects.all():
        if not loc.created_at:
            loc.created_at = default_date
            loc.created_by = loc.owner

        if not loc.updated_at:
            loc.updated_at = loc.created_at
            loc.updated_by = loc.created_by

        loc.save()

    Org= apps.get_model('orgs', 'Organization')

    for org in Org.objects.all():
        if not org.created_at:
            org.created_at = default_date
            org.created_by = loc.owner

        if not org.updated_at:
            org.updated_at = loc.created_at
            org.updated_by = loc.created_by

        org.save()

    Activity = apps.get_model('orgs', 'Activity')
    for act in Activity.objects.all():
        if not act.created_at:
            act.created_at = default_date
            act.created_by = loc.owner

        if not act.updated_at:
            act.updated_at = loc.created_at
            act.updated_by = loc.created_by

        act.save()

        Session = apps.get_model('orgs', 'Session')
        for sess in Session.objects.filter(activity=act):
            if not sess.created_at:
                sess.created_at = default_date
                sess.created_by = loc.owner

            if not sess.updated_at:
                sess.updated_at = loc.created_at
                sess.updated_by = loc.created_by

            sess.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0067_activity_created_at_activity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_activities', to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orgs', to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orgs', to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to='orgs.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sessions', to='orgs.profile'),
        ),
        migrations.RunPython(backfill_fields),
    ]
    
