# Generated by Django 6.0.2 on 2026-03-30 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0068_alter_activity_created_by_alter_activity_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='migrated_from_event',
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 3, 30)),
        ),
    ]
