# Generated by Django 5.1.3 on 2026-09-02 20:28

import orgs.services.helper_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0068_video_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(blank=True, default=orgs.services.helper_function.default_expire_date, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('BLOCKED_HOURLY', 'Blocked Hourly'), ('BLOCKED_MONTHLY', 'Blocked Monthly'), ('DISABLED', 'Email Disabled'), ('FAILED', 'Send Failed'), ('PENDING', 'Pending')], default='SENT', max_length=30),
        ),
    ]
