# Generated by Django 5.1.3 on 2026-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0069_alter_activity_expire_date_alter_emaillog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='interest_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
