# Generated by Django 6.0.2 on 2026-03-30 14:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0070_alter_organization_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
