# Generated by Django 5.1.3 on 2026-10-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0070_activity_interest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.activity'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.location'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('page_view', 'Page view'), ('activity_view', 'Activity viewed'), ('organization_view', 'Organization viewed'), ('org_enroll', 'Organization enrollment'), ('favorite_add', 'Favorite added'), ('favorite_remove', 'Favorite removed'), ('interest_click', 'Interest click'), ('volunteer_signup', 'Volunteer signup'), ('volunteer_signup_cancel', 'Volunteer signup cancelled'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password reset'), ('password_change', 'Password change'), ('profile_update', 'Profile update'), ('org_update', 'Organization update'), ('activity_update', 'Activity update'), ('session_update', 'Session update'), ('location_update', 'Location update'), ('upload_activity', 'Activity upload'), ('upload_location', 'Location upload'), ('feedback', 'Feedback submitted')], max_length=50),
        ),
    ]
