# Generated by Django 6.0.2 on 2026-03-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0071_alter_activity_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
            ],
        ),
    ]
