# Generated by Django 6.0.2 on 2026-04-02 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0072_alter_activity_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 2)),
        ),
    ]
