# Generated by Django 6.0.2 on 2026-04-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0075_alter_activity_expire_date_stagingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingactivity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
    ]
