# Generated by Django 6.0.2 on 2026-04-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0076_stagingactivity_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityupload',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='orgs.organization'),
        ),
    ]
