# Generated by Django 5.1.3 on 2026-04-08 14:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0077_activityupload_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_loc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 8)),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_locs', to='orgs.profile'),
        ),
        migrations.CreateModel(
            name='Pending_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('date_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expire_date', models.DateField(default=datetime.date(2027, 4, 8))),
                ('activity_url', models.URLField(blank=True, default='')),
                ('no_cost', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, to='orgs.eventcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_activities', to='orgs.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_activities', to='orgs.organization')),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_activities', to='orgs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=255, unique=True)),
                ('physical_location', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='WI', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('org_loc_url', models.URLField(blank=True, default='')),
                ('location_about', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('norm_loc_name', models.CharField(blank=True, max_length=255)),
                ('norm_address', models.CharField(blank=True, max_length=255)),
                ('norm_city', models.CharField(blank=True, max_length=100)),
                ('norm_state', models.CharField(blank=True, max_length=2)),
                ('fingerprint', models.CharField(blank=True, max_length=500, unique=True)),
                ('county_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.county')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_locations', to='orgs.profile')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_locations', to='orgs.organization')),
                ('real_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.location')),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_locations', to='orgs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_format', models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('b', 'Hybrid')], max_length=1)),
                ('session_url', models.URLField(blank=True, default='')),
                ('ongoing', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sessions', to='orgs.pending_activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_sessions', to='orgs.profile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_sessions', to='orgs.pending_location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_sessions', to='orgs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RawLoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('date_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expire_date', models.DateField(default=datetime.date(2027, 4, 8))),
                ('activity_url', models.URLField(blank=True, default='')),
                ('no_cost', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
            ],
        ),
        migrations.DeleteModel(
            name='StagingActivity',
        ),
        migrations.AddConstraint(
            model_name='pending_location',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='unique_pending_location_fp'),
        ),
    ]
