# Generated by Django 5.1.3 on 2026-04-06 16:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0077_activityupload_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 6)),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='RawLoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('date_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expire_date', models.DateField(default=datetime.date(2027, 4, 6))),
                ('activity_url', models.URLField(blank=True, default='')),
                ('no_cost', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
            ],
        ),
        migrations.DeleteModel(
            name='StagingActivity',
        ),
    ]
