# Generated by Django 5.1.3 on 2026-04-06 17:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0078_alter_activity_expire_date_alter_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('v', 'Volunteer Opportunity'), ('t', 'Training')], max_length=1)),
                ('date_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expire_date', models.DateField(default=datetime.date(2027, 4, 6))),
                ('activity_url', models.URLField(blank=True, default='')),
                ('no_cost', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, to='orgs.eventcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_activities', to='orgs.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_activities', to='orgs.organization')),
                ('real_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.location')),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
                ('time_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.commitment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_activities', to='orgs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=255, unique=True)),
                ('physical_location', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, choices=[('C', 'Central'), ('EC', 'East Central'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SC', 'South Central'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('St', 'Statewide')], max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='WI', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('org_loc_url', models.URLField(blank=True, default='')),
                ('location_about', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('county_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.county')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_locations', to='orgs.profile')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_locations', to='orgs.organization')),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.activityupload')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_locations', to='orgs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_format', models.CharField(choices=[('o', 'Online'), ('i', 'InPerson'), ('b', 'Hybrid')], max_length=1)),
                ('session_url', models.URLField(blank=True, default='')),
                ('ongoing', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.pending_activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_sessions', to='orgs.profile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.pending_location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pending_sessions', to='orgs.profile')),
            ],
        ),
    ]
