# Generated by Django 5.1.3 on 2026-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0078_location_fingerprint_location_norm_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='unique_location_fp'),
        ),
    ]
