# Generated by Django 5.1.3 on 2026-04-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0079_pending_activity_pending_location_pending_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_activity',
            name='real_location',
        ),
        migrations.AddField(
            model_name='pending_location',
            name='real_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.location'),
        ),
    ]
