# Generated by Django 5.1.3 on 2026-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0080_remove_pending_activity_real_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_session',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
