# Generated by Django 5.1.3 on 2026-04-07 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0081_pending_session_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 7)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 7)),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pending_sessions', to='orgs.pending_location'),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 7)),
        ),
    ]
