# Generated by Django 5.1.3 on 2026-04-08 13:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0082_alter_activity_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_location',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='pending_location',
            name='norm_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pending_location',
            name='norm_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pending_location',
            name='norm_loc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pending_location',
            name='norm_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 8)),
        ),
        migrations.AlterField(
            model_name='pending_activity',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 8)),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sessions', to='orgs.pending_activity'),
        ),
        migrations.AlterField(
            model_name='pending_session',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_sessions', to='orgs.pending_location'),
        ),
        migrations.AlterField(
            model_name='rawloaddata',
            name='expire_date',
            field=models.DateField(default=datetime.date(2027, 4, 8)),
        ),
    ]
