# Generated by Django 5.1.3 on 2026-04-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0083_pending_location_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_loc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='norm_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_locs', to='orgs.profile'),
        ),
        migrations.AddConstraint(
            model_name='pending_location',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='unique_pending_location_fp'),
        ),
    ]
